### ISSUE TITLE
Add splash screen activity

### ISSUE THREAD

**Issue by suyalamritanshu** [suyalamritanshu/Juit-College#2]

**Comment by SiddyDevelops** [comment]
@suyalamritanshu Hello, I would like to work on this issue, can you please assign it to me ?

**Comment by suyalamritanshu** [comment]
@SiddyDevelops issue is yours

**Comment by SiddyDevelops** [comment]
@suyalamritanshu Sir I have generated a PR #4. Please review it. I have also attached screen rec along with my PR. Also sir please kindly add the ```hactober-accepted``` label. Thank you.

**Comment by SiddyDevelops** [comment]
@suyalamritanshu Sir I have updated the logo and generated a PR #5 . Please review it.
